memory_limit=256M
upload_max_filesize=2048M
post_max_size=2048M
short_open_tag=On

[opcache]
; enable opcache
opcache.enable=1
; enable opcache for cli
opcache.enable_cli=1
; enable faster shutdown, is set to false (0) by default
opcache.fast_shutdown=1
; re-validate of timestamps frequency, is set to 2 by default
opcache.revalidate_freq=0
; validate timestamps on each request, is set to true (1) by default
opcache.validate_timestamps=${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-0}
; save comments, is set to false (0) by default
opcache.save_comments=0
; enable file cache, is set to false (0) by default
opcache.file_cache_fallback=1
; maximum memory can use to store compiled PHP files, Symfony recommends 256
opcache.memory_consumption=256
; interned strings buffer, is set to 4 by default
opcache.interned_strings_buffer=16
; maximum number of files that can be stored in the cache, Symfony recommends 10000
opcache.max_accelerated_files=356512
; maximum time a file is allowed to be in the cache, is set to 0 by default
opcache.max_wasted_percentage=15

[mysqld]
; from 9 to reduce threads_created RPhr of 78
thread_cache_size=100
; from 16K to reduce # packets per hour
net_buffer_length=32K
; from 1M to conserve RAM because the QCtype of OFF
query_cache_size=0
; from OFF to allow awareness and proactively correct
slow_query_log=1
; from 10 seconds - if overwhelmed with entries, raise the seconds by 1
long_query_time=1
; from 4 to expedite writing to tables on storage devices
innodb_write_io_threads=64
