services:
  web:
    image: php:8.3-apache
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        HOST_UID: "${HOST_UID:-33}"
        HOST_GID: "${HOST_GID:-33}"
    container_name: '${APP_NAME}_web'
    hostname: web
    restart: unless-stopped
    environment:
      PHP_SESSION_SAVE_PATH: "${PHP_SESSION_HOST:-memcached:11211}"
      PHP_SESSION_NAME: "${PHP_SESSION_NAME:-BASICSESSID}"
      BASIC_APP_ENV: "${BASIC_APP_ENV:-prod}"
    ports:
      - "8090:80"
    volumes:
      - ./web:/var/www/html/
      - ./log/apache2:/var/log/apache2/
    networks:
      - internal
      - external

networks:
  internal:
  external:
    driver: bridge
