#!/bin/bash

# Include bash base scripts
. bin/_base.sh
. bin/_colors.sh

if test -f ".env"
then
    echo "${underline}${green}The environment file \".env\" already exists!${reset}"

    read -p "${orange}Recreate environment file (y/n)? ${reset}"
    if [[ "$REPLY" == "y" ]]
    then
        rm -f .env
    else
        exit;
    fi
fi

# Get the slug
slug="$1"

if [[ "$slug" == "" ]]
then
    read -p "${orange}Enter environment slug (default: ${_slug}): ${reset}" slug
    slug=${slug:-"${_slug}"}
fi
echo "${green}The environment slug \"${slug}\" will be used.${reset}"

# Fix the slug if wrong given
slug=${slug// /-}
#slug=${slug,,} MacOS bash 3.2 fail!
slug=$(echo "$slug" | tr '[:upper:]' '[:lower:]')

# Create a session prefix from slug
spre=${slug//[^[:alpha:]]/}
#spre=${spre^^} MacOS bash 3.2 fail!
spre=$(echo "$spre" | tr '[:lower:]' '[:upper:]')

# Get the domain
domain="$2"

if [[ "$domain" == "" ]]
then
    read -p "${orange}Enter your domain (default: ${_domain}): ${reset}" domain
    domain=${domain:-"${_domain}"}
fi
echo "${green}The domain \"${blue}${underline}${domain}${nounderline}${green}\" will be used.${reset}"

# Get the environment type
environment="$2"

if [[ "$environment" == "" ]]
then
    read -p "${orange}Enter your environment type ([dev|prod|test] default: prod): ${reset}" environment
    environment=${environment:-prod}
fi
echo "${green}The environment is running in \"${environment}\" mode.${reset}"

if [[ "$environment" == "prod" ]]
then
    docker_compose_environment_files="docker-compose.yml"
else
    docker_compose_environment_files="docker-compose.yml:docker-compose.dev.yml:docker-compose.mariadb.yml:docker-compose.memcache.yml:docker-compose.adminer.yml"
fi

# Read the latest application version from git tags
git_tag_latest=`git rev-list --tags --max-count=1`

if [[ "$git_tag_latest" != "" ]]
then
    application_version=`git describe --tags ${git_tag_latest}`
else
    application_version="0.0.0"
fi

random_string ()
{
    cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1
}

db_port="3306"
db_user="${slug}"
db_password=$(random_string 16)
db_database="${slug//-/_}"

{
    echo "## Environment settings";
    echo "## This file is generated by the \"env.sh\" script!";
    echo "";

    echo "## Docker Compose file configuration";
    echo COMPOSE_DIR=.;
    echo COMPOSE_PROJECT_NAME=basic;
    echo COMPOSE_FILE=${docker_compose_environment_files};
    echo "";

    echo "## Host specific settings";
    echo HOST_UID=`id -u`;
    echo HOST_GID=`id -g`;
    echo "";

    echo "## Application ports";
    echo APP_PORT=8090;
    echo ADMINER_PORT=8091;
    echo PHPMYADMIN_PORT=8092;
    echo "";

    echo "## Database specific settings (Sqlite, MariaDB etc.)";
    echo DB=mariadb;
    echo DB_HOST=db;
    echo DB_PORT=${db_port};
    echo DB_ROOT_PASSWORD=$(random_string 32);
    echo DB_NAME=${db_database};
    echo DB_USER=${db_user};
    echo DB_PASSWORD=${db_password};
    echo "DB_DSN=mysql://${db_user}:${db_password}@mariadb:${db_port}/${db_database}";
    echo "";

    echo "## PHP specific settings";
    echo OPCACHE_VALIDATE_TIMESTAMPS=1;
    echo PHP_SESSION_SAVE_PATH=memcached:11211;
    echo PHP_SESSION_NAME="${spre}_SESSION_ID";
    echo "";

    echo "## Environment slug and domain";
    echo APP_SLUG="${slug}";
    echo APP_NAME="${slug}";
    echo APP_DOMAIN="${domain}";
    echo APP_DIR="$PWD";
    echo "";

    echo "## Application specific settings and secrets";
    echo APP_VERSION=${application_version};
    echo APP_ENV=${environment};
    echo APP_SECRET=$(random_string);
    echo APP_JWT_PASSPHRASE=$(random_string);
} > .env;
