name: PHPUnit tests

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        working-directory: ./public
        run: composer validate

      - name: Install dependencies
        working-directory: ./public
        run: composer --no-progress --optimize-autoloader --prefer-dist --ignore-platform-reqs --verbose install

      - name: Run PHPUnit Tests
        working-directory: ./public
        run: php ./vendor/bin/phpunit tests
