<?php

/**
 * Authenticate a user against a password file generated by Apache's httpasswd
 * using PHP rather than Apache itself.
 *
 * @param string $user The submitted user name
 * @param string $pass The submitted password
 * @param string $pass_file='.htpasswd' The system path to the htpasswd file
 * @param string $crypt_type='DES' The crypt type used to create the htpasswd file
 * @return bool
 */
function http_authenticate ($user, $pass, $pass_file = '.htpasswd', $crypt_type = 'DES') {
    // the stuff below is just an example useage that restricts
    // user names and passwords to only alpha-numeric characters.
    if (!ctype_alnum($user)) {
        // invalid user name
        return false;
    }

    if (!ctype_alnum($pass)) {
        // invalid password
        return false;
    }

    // get the information from the htpasswd file
    if (file_exists($pass_file) && is_readable($pass_file)) {
        // the password file exists, open it
        if ($fp = fopen($pass_file,'r')) {
            while ($line=fgets($fp)) {
                // for each line in the file remove line endings
                $line = preg_replace('`[\r\n]$`', '', $line);
                list($fuser, $fpass) = explode(':', $line);
                if ($fuser == $user) {
                    // the submitted user name matches this line
                    // in the file
                    switch ($crypt_type) {
                        case 'DES':
                            // the salt is the first 2
                            // characters for DES encryption
                            $salt = substr($fpass, 0,2);
                            // use the salt to encode the
                            // submitted password
                            $test_pw = crypt($pass, $salt);
                            break;
                        case 'PLAIN':
                            $test_pw = $pass;
                            break;
                        case 'SHA':
                        case 'MD5':
                        default:
                            // unsupported crypt type
                            fclose($fp);
                            return false;
                    }

                    if ($test_pw == $fpass) {
                        // authentication success.
                        fclose($fp);
                        return true;
                    } else {
                        return false;
                    }
                }
            }

            fclose($fp);
        } else {
            // could not open the password file
            return false;
        }
    } else {
        return false;
    }
}

/**
 * Give back a array with the characters, that can be used by string generation
 * 
 * @param string $omit A string of characters to be ignored
 * @param string $case Default are both cases, lower use only lower-case letters, upper or capital use only capital 
 *                     letters.
 * @param boolean $special_characters If special characters are involved
 */
function get_gen_chars ($omit = 'lIO017', $case = 'both', $special_characters = false)
{
    $dummy = array_merge(
        range('0', '9'),
        (($case == 'lower' || $case == 'both') ? range('a', 'z') : array()),
        (($case == 'capital' || $case == 'upper' || $case == 'both') ? range('A', 'Z') : array()),
        ($special_characters === true ? array('#', '&', '@', '$', '_', '%', '?', '+') : array())
    );
    $chrs = array();

    // no lIO017: omitting potentially confusable ones
    foreach ($dummy as $key => $value)
        if (strpos($omit, (string)$value) === false)
            $chrs[] = (string)$value;

    return $chrs;
}

/**
 * Generate a random string to use it for password or other authentication keys
 * 
 * Examples:
 * 
 * » Password with 6 numbers, lower case and upper case letters, spezial characters:
 *   strtolower(rand_string(6)),
 * 
 * » Url stable string 16 characters long:
 *   get_gen_string(16, true, true, false);
 * 
 * » Authentication key with 7 numbers and lower case letters:
 *   get_gen_string(7, true, false, true)
 * 
 * @param integer $length
 * @param bool    $number
 * @param bool    $lower_case
 * @param bool    $upper_case
 * @param bool    $special_characters
 * @return string
 */
function get_gen_string ($length = 8, $number = true, $lower_case = true, $upper_case = true, $special_characters = false)
{
    if ($lower_case === true && $upper_case === true) {
        $case = 'both';
    } elseif ($lower_case === true && $upper_case === false) {
        $case = 'lower';
    } elseif ($lower_case === false && $upper_case === true) {
        $case = 'upper';
    }

    $dummy = get_gen_chars('lIO017', $case, $special_characters);

    // shuffle array
    mt_srand((double)microtime()*1000000);

    for ($i = 1; $i <= (count($dummy) * 2); $i++) {
        $swap = mt_rand(0, (count($dummy) - 1));
        $tmp = $dummy[$swap];
        $dummy[$swap] = $dummy[0];
        $dummy[0] = $tmp;
    }

    $string = substr(implode('', $dummy), 0, $length);

    if ($number === true && !preg_match('/[0-9]/', $string)) {
        $string = get_gen_string($length, $number, $lower_case, $upper_case, $special_characters);
    }

    if ($lower_case === true && !preg_match('/[a-z]/', $string)) {
        $string = get_gen_string($length, $number, $lower_case, $upper_case, $special_characters);
    }

    if ($upper_case === true && !preg_match('/[A-Z]/', $string)) {
        $string = get_gen_string($length, $number, $lower_case, $upper_case, $special_characters);
    }

    if ($special_characters === true && !preg_match('/[#&@$_%?+]/', $string)) {
        $string = get_gen_string($length, $number, $lower_case, $upper_case, $special_characters);
    }

    // get the string
    return $string;
}

if (isset($_POST['username']) && !empty($_POST['username'])) {
    $username = $_POST['username'];
} else {
    $username = '';
}

// Password to be encrypted for a .htpasswd file
if (!isset($_POST['password']) || empty($_POST['password'])
    || (isset($_POST['action'])
        && $_POST['action'] == 'generate')
) {
    $password_clear = get_gen_string(8);
} else {
    $password_clear = $_POST['password'];
}

// Encrypt password
//$password = crypt($clearTextPassword, base64_encode($clearTextPassword));
$password_crypt = crypt($password_clear);

echo '<?xml version="1.0" encoding="UTF-8" ?>';

?><html xml:lang="de" xmlns="http://www.w3.org/1999/xhtml">
    <head profile="http://gmpg.org/xfn/11">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="language" content="de">
        <title>Passwordgenerator</title>
        <style>
        <!--

        body {
            padding: 10px;
            font: normal normal normal 11px/11px "Bitstream Vera Sans", Tahoma, Verdana, Helvetica, Arial, sans-serif;
            color: #001024;
        }

        form {
            display: block;
            padding-bottom: 10px;
        }

        input[type=text] {
            width: 240px;
        }

        table.params {
            border-collapse: collapse;
        }

        table.params td {
            padding: 1px 5px;
            border: 1px solid #ddd;
        }

        table.params td:first-child {
            text-align: right;
        }

        pre {
            margin: 0;
            padding: 0;
            font: normal normal normal 11px/11px "Bitstream Vera Sans Mono",Consolas,"Andale Mono WT","Andale Mono","Lucida Console",Monaco,"Courier New",Courier,monospace;
        }

        -->
        </style>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <form action="" method="post">
        <table>
            <tr>
                <td>username:</td>
                <td><input type="text" name="username" value="<?php echo $username; ?>" /></td>
            </tr>
            <tr>
                <td>password:</td>
                <td><input type="text" name="password" value="<?php echo $password_clear; ?>" /></td>
            </tr>
            <tr>
                <td>encrypted:</td>
                <td><pre><?php echo $password_crypt; ?></pre></td>
            </tr>
            <tr>
                <td>htpasswd:</td>
                <td><pre><?php echo $username; ?>:<?php echo $password_crypt; ?></pre></td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" name="action" value="encrypt" />
                    <input type="submit" name="action" value="generate" />
                </td>
            </tr>
        </table>
        </form>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="//code.jquery.com/jquery.js"></script>

        <!-- Latest compiled and minified JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    </body>
</html>